config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"
  resources :questions, only: [:index, :show]
  get 'follow_user', to: 'users#follow_user'
  get 'unfollow_user', to: 'users#unfollow_user'
  get 'follow_topic', to: 'users#follow_theme'
  get 'unfollow_topic', to: 'users#unfollow_theme'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	belongs_to :user
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/answer.rb
class Answer < ApplicationRecord

belogs_to :question
belogs_to :user
  
end

app/models/follow.rb
class Follow < ApplicationRecord
  belogns_to :follower, foreign_key: 'user_id',class_name: 'User'
  belongs_to :following,foreign_key: 'following_id', class_name: 'User'
  
end

app/models/follow_theme.rb
class FollowTheme < ApplicationRecord
	belongs_to :user
	belongs_to :theme
end 

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	belongs_to :theme
	has_many :answers
end 

app/models/theme.rb
class Theme < ApplicationRecord

has_many :questions
has_many :follows, as: :followable
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :follows
  has_many :follower_relationship, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationship, source: :followers
  has_many :following_relationship, foreign_key: :user_id, class_name: 'Follow'
  has_many :following, through: :following_relationship, source: :following


  has_many :topics, class_name: 'Theme'
  has_many :answers
  has_many :questions
  has_many :follow_themes
  has_many :followed_themes, through: :follow_themes, source: :theme
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController< ApplicationController
	def index
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!

    def index
        @questions = Question.all
    end

    def show
        @question = Question.find_by(id: params[:id])
        @answers = @question.answers
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def follow_user
      current_user.follows.create(following_id: params[:user_id])
      byebug
      redirect_to question_path(params[:question_id])
    end

    def unfollow_user
        follow = current_user.follows.find_by(following_id: params[:user_id])
        if follow.present?
          follow.destroy
        end
        redirect_to question_path(params[:question_id])
    end

    def follow_theme
        current_user.follow_themes.create(theme_id: params[:theme_id])
        redirect_to question_path(params[:question_id])
    end

    def unfollow_theme
        follow_theme = current_user.follow_themes.find_by(theme_id:params[:theme_id])
        if follow_theme.present?
            follow_theme.destroy
        end
        redirect_to question_path(params[:question_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
Hello Welcome to Quora App

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoraTestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<% if current_user.present? %>
	<%= link_to "Logout", destroy_user_session_path(current_user), method: :delete %>
<% end %>

app/views/questions/index.html.erb
<h1>Listing Questions</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Topic</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @questions.each do |question| %>
		<tr>
			<td><%= link_to question.name, question_path(question), class: "question" %></td>
			<td><%= question.theme.description %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br>

app/views/questions/show.html.erb
<%= @question.user.email %>:
<% unless current_user.follows.find_by(following_id: @question.user.id).present? %>

 <%= link_to "follow_user", follow_user_path(user_id: @question.user.id, question_id: @question.id), class: "follow_user" %>
<% else %>
<%= link_to "unfollow user", unfollow_user_path(user_id: @question.user.id,question_id: @question.id) %>
<% end %><br>
<%= @question.theme.description %>:
<% unless current_user.follow_themes.find_by(theme_id: @question.theme.id).present? %>
  <%=  link_to "follow topic", follow_topic_path(theme_id: @question.theme.id,question_id: @question.id), class: "follow_topic" %>
<% else %>

<%= link_to "unfollow topic", unfollow_topic_path(theme_id: @question.theme.id,question_id: @question.id) %>
<% end %>

<h1> Question Test </h1>
<p> <%= @question.name %> </p>
<h2> Answers to above question </h2>

<% @answers.each do |answer| %>
<p class="answer"> <%= answer.description %></p><br>
  <% end %>